logging:
  level:
    com.bairei: DEBUG

spring.data.mongodb:
  host: ${SPRING_DATA_MONGODB_HOST:localhost}
  port: ${SPRING_DATA_MONGODB_PORT:27017}
  database: ${SPRING_DATA_MONGODB_DATABASE:collector}
  username: ${SPRING_DATA_MONGODB_USERNAME:bairei}
  password: ${SPRING_DATA_MONGODB_PASSWORD:somerandompasswordnoonewillguess}